# Generated by Django 5.1.7 on 2025-10-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('following', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('athlete', 'Athlete Story'), ('event', 'Event'), ('medal', 'Medal Result'), ('inspiration', 'Inspiration'), ('other', 'Other')], default='other', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cabangOlahraga', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='following.cabangolahraga')),
            ],
        ),
    ]
