# Generated by Django 5.2.7 on 2025-10-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_berita_cabangolahraga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='date',
            new_name='created_at',
        ),
    ]
