# Generated by Django 5.1.7 on 2025-10-24 08:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('following', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Tournament Name')),
                ('description', models.TextField(verbose_name='Description of the Tournament')),
                ('sport_branch', models.CharField(choices=[('tennis', 'Tennis'), ('swim', 'Swimming'), ('ath', 'Athletics'), ('basket', 'Wheelchair Basketball'), ('other', 'Other')], default='other', max_length=10, verbose_name='Cabang Olahraga')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location / Venue (Optional)')),
                ('picture_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Tournament Image URL')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Time Ends (Optional)')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('event_type', models.CharField(choices=[('global', 'Global Tournament (Admin Only)'), ('community', 'Community Tournament')], default='community', max_length=10, verbose_name='Event Scope')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabangOlahraga', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='following.cabangolahraga')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Tournament Event',
                'verbose_name_plural': 'Tournament Events',
                'ordering': ['start_time'],
            },
        ),
    ]
