# Generated by Django 5.1.7 on 2025-10-22 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Tournament Name')),
                ('description', models.TextField(verbose_name='Description of the Tournament')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location / Venue (Optional)')),
                ('official_link', models.URLField(blank=True, null=True, verbose_name='Official Website Link (Recommended for Global Tournaments)')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('event_type', models.CharField(choices=[('global', 'Global Tournament (Admin Only)'), ('community', 'Community Tournament')], default='community', max_length=10, verbose_name='Event Scope')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Tournament Event',
                'verbose_name_plural': 'Tournament Events',
                'ordering': ['start_time'],
            },
        ),
    ]
