# Generated by Django 5.1.7 on 2025-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_end_time_event_picture_url_alter_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sport_branch',
            field=models.CharField(choices=[('tennis', 'Tennis'), ('swim', 'Swimming'), ('ath', 'Athletics'), ('basket', 'Wheelchair Basketball'), ('other', 'Other')], default='other', max_length=10, verbose_name='Cabang Olahraga'),
        ),
    ]
