# Generated by Django 5.2.7 on 2025-10-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_end_time_event_picture_url_alter_event_creator'),
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cabangOlahraga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='following.cabangolahraga'),
            preserve_default=False,
        ),
    ]
