# Generated by Django 5.1.7 on 2025-10-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_sport_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='official_link',
        ),
    ]
