# Generated by Django 5.2.7 on 2025-10-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_cabangolahraga'),
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cabangOlahraga',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='following.cabangolahraga'),
        ),
    ]
