# Generated by Django 5.2.7 on 2025-10-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_cabangolahraga'),
        ('event', '0004_remove_event_official_link'),
    ]

    operations = [
    ]
