# Generated by Django 5.1.7 on 2025-10-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_type', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=255)),
                ('medal_date', models.CharField(max_length=50)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medali', to='profil_atlet.atlet')),
            ],
        ),
    ]
