# Generated by Django 5.2.7 on 2025-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_atlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
