# Generated by Django 5.2.7 on 2025-11-26 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0002_remove_following_priority_alter_cabangolahraga_name'),
        ('profil_atlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atlets', to='following.cabangolahraga'),
        ),
    ]
