# Generated by Django 5.2.7 on 2025-11-26 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
