# Generated by Django 5.2.7 on 2025-10-23 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_delete_cabangolahraga_delete_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(editable=False, max_length=100)),
                ('name', models.TextField()),
                ('picture', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
