# Generated by Django 5.2.7 on 2025-12-07 22:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
