# Generated by Django 5.2.7 on 2025-12-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture_public_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
