# Generated by Django 5.2.7 on 2025-10-23 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_alter_user_name_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(editable=False, max_length=100)),
                ('name', models.TextField(null=True)),
                ('picture', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
