# Generated by Django 5.2.7 on 2025-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='priority',
        ),
        migrations.AlterField(
            model_name='cabangolahraga',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
